package main

import (
	"log"
	"net/http"
	"os"
	"strings"
	"time"
)

func DetectPlatform() (bool, string) {
	if IsProxmox() {
		return true, "proxmox"
	}
	if IsOpenStack() {
		return true, "openstack"
	}
	if IsSolusVM() {
		return true, "solusvm"
	}
	return false, ""
}

func IsProxmox() bool {
	// Check for Proxmox-specific MAC address prefix BC:24:11
	entries, err := os.ReadDir("/sys/class/net")
	if err == nil {
		for _, entry := range entries {
			if entry.Name() == "lo" {
				continue
			}
			if data, err := os.ReadFile("/sys/class/net/" + entry.Name() + "/address"); err == nil {
				mac := strings.ToUpper(strings.TrimSpace(string(data)))
				if strings.HasPrefix(mac, "BC:24:11") {
					log.Println("[Platform][Proxmox] Found default Proxmox MAC prefix (heuristic)")
					return true
				}
			}
		}
	}

	return false
}

func IsSolusVM() bool {
	// Check for "Generated by SolusVM" comments in common config files
	filesToCheck := []string{
		"/etc/sysconfig/network",
		"/etc/sysconfig/network-scripts/ifcfg-eth0",
		"/etc/hosts",
		"/etc/network/interfaces",
		"/etc/hostname",
	}

	for _, file := range filesToCheck {
		if data, err := os.ReadFile(file); err == nil {
			content := string(data)
			if strings.Contains(content, "Generated by SolusVM") ||
				strings.Contains(content, "SolusVM") {
				log.Println("[Platform][SolusVM] Found SolusVM signature in", file)
				return true
			}
		}
	}

	return false
}

func IsOpenStack() bool {
	// Try to reach OpenStack metadata service (with timeout)
	client := http.Client{Timeout: 5 * time.Second}
	resp, err := client.Get("http://169.254.169.254/openstack/")
	if err == nil {
		resp.Body.Close()
		log.Println("[Platform][OpenStack] Metadata endpoint found: http://169.254.169.254 ")
		return true
	}

	// Check for config drive
	if _, err := os.Stat("/dev/disk/by-label/config-2"); err == nil {
		log.Println("[Platform][OpenStack] Config drive found /dev/disk/by-label/config-2")
		return true
	}

	dmiPaths := []string{
		"/sys/class/dmi/id/product_name",
		"/sys/class/dmi/id/chassis_asset_tag",
	}

	for _, path := range dmiPaths {
		if data, err := os.ReadFile(path); err == nil {
			if strings.Contains(strings.ToLower(string(data)), "openstack") {
				log.Println("[Platform][OpenStack] DMI contains openstack")
				return true
			}
		}
	}

	return false
}
